#cloud-config
write_files:
  - path: /var/lib/cloud/instance/scripts/mariadb.sh
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      export DEBIAN_FRONTEND="noninteractive"
      export PASSWORD="{{ passwd }}"

      
      apt-get install software-properties-common
      apt update
      apt install -yq mariadb-server
  - path: /var/lib/cloud/instance/scripts/mariadbvars
    permissions: '0755'
    content: |
      
      Y
      {{ passwd }}
      {{ passwd }}
      Y
      n
      Y
      Y

      
runcmd:
  - apt update
  - export DEBIAN_FRONTEND=noninteractive 
  - apt -yq upgrade
  - ufw enable
  - ufw allow 22
  - ufw allow 3306
  - chmod +x /var/lib/cloud/instance/scripts/mariadb.sh
  - /var/lib/cloud/instance/scripts/mariadb.sh
  - 'cat /var/lib/cloud/instance/scripts/mariadbvars | mysql_secure_installation'
  - sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - mysql -uroot -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; GRANT ALL PRIVILEGES ON *.* TO "root"@"%"  IDENTIFIED BY "{{ passwd }}" WITH GRANT OPTION; FLUSH PRIVILEGES;'
  - service mysql restart
  - rm -r /var/lib/cloud/instance/scripts/*